"""add shooting state to games

Revision ID: 873a57bb42c0
Revises: acf42ed34180
Create Date: 2026-09-21 11:50:10.890170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '873a57bb42c0'
down_revision: Union[str, Sequence[str], None] = 'acf42ed34180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('own_shots', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('opponent_shots', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('target_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('games', sa.Column('pending_shot', sa.String(length=3), nullable=True))
    op.add_column('games', sa.Column('turn', sa.String(length=20), nullable=True))

    op.execute(
        "UPDATE games "
        "SET own_shots = '{}' ::jsonb "
        "WHERE own_shots IS NULL"
    )
    op.execute(
        "UPDATE games "
        "SET opponent_shots = '{}' ::jsonb "
        "WHERE opponent_shots IS NULL"
    )
    op.execute(
        "UPDATE games "
        "SET target_hits = '[]' ::jsonb "
        "WHERE target_hits IS NULL"
    )
    op.execute(
        "UPDATE games "
        "SET turn = 'unknown' "
        "WHERE turn IS NULL"
    )

    op.alter_column(
        'games',
        'own_shots',
        nullable=False
    )
    op.alter_column(
        'games',
        'opponent_shots',
        nullable=False
    )
    op.alter_column(
        'games',
        'target_hits',
        nullable=False
    )
    op.alter_column(
        'games',
        'turn',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'turn')
    op.drop_column('games', 'pending_shot')
    op.drop_column('games', 'target_hits')
    op.drop_column('games', 'opponent_shots')
    op.drop_column('games', 'own_shots')
    # ### end Alembic commands ###
