"""add ships to games

Revision ID: acf42ed34180
Revises: 97a0a6c8817a
Create Date: 2026-09-07 08:36:11.674008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acf42ed34180'
down_revision: Union[str, Sequence[str], None] = '97a0a6c8817a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('ships', postgresql.JSONB(), nullable=True))

    op.execute(
        "UPDATE games SET ships = '[]'::jsonb "
        "WHERE ships IS NULL"
    )

    op.alter_column(
        'games',
        'ships',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'ships')
    # ### end Alembic commands ###
